const aslSigns = {
  A: { image: "assets/ASL/A.png" },
  B: { image: "assets/ASL/B.png" },
  C: { image: "assets/ASL/C.png" },
  D: { image: "assets/ASL/D.png" },
  E: { image: "assets/ASL/E.png" },
  F: { image: "assets/ASL/F.png" },
  G: { image: "assets/ASL/G.png" },
  H: { image: "assets/ASL/H.png" },
  I: { image: "assets/ASL/I.png" },
  J: { image: "assets/ASL/J.png" },
  K: { image: "assets/ASL/K.png" },
  L: { image: "assets/ASL/L.png" },
  M: { image: "assets/ASL/M.png" },
  N: { image: "assets/ASL/N.png" },
  O: { image: "assets/ASL/O.png" },
  P: { image: "assets/ASL/P.png" },
  Q: { image: "assets/ASL/Q.png" },
  R: { image: "assets/ASL/R.png" },
  S: { image: "assets/ASL/S.png" },
  T: { image: "assets/ASL/T.png" },
  U: { image: "assets/ASL/U.png" },
  V: { image: "assets/ASL/V.png" },
  W: { image: "assets/ASL/W.png" },
  X: { image: "assets/ASL/X.png" },
  Y: { image: "assets/ASL/Y.png" },
  Z: { image: "assets/ASL/Z.png" },
};

module.exports = { aslSigns };
