const bucket = require("../utils/firebaseAdmin");

const inversePslMapping = {
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fا.png?alt=media`]:
    "ا",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fب.png?alt=media`]:
    "ب",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fپ.png?alt=media`]:
    "پ",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fت.png?alt=media`]:
    "ت",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fٹ.png?alt=media`]:
    "ٹ",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fث.png?alt=media`]:
    "ث",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fج.png?alt=media`]:
    "ج",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fچ.png?alt=media`]:
    "چ",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fح.png?alt=media`]:
    "ح",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fخ.png?alt=media`]:
    "خ",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fد.png?alt=media`]:
    "د",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fڈ.png?alt=media`]:
    "ڈ",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fذ.png?alt=media`]:
    "ذ",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fر.png?alt=media`]:
    "ر",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fڑ.png?alt=media`]:
    "ڑ",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fز.png?alt=media`]:
    "ز",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fژ.png?alt=media`]:
    "ژ",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fس.png?alt=media`]:
    "س",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fش.png?alt=media`]:
    "ش",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fص.png?alt=media`]:
    "ص",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fض.png?alt=media`]:
    "ض",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fط.png?alt=media`]:
    "ط",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fظ.png?alt=media`]:
    "ظ",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fع.png?alt=media`]:
    "ع",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fغ.png?alt=media`]:
    "غ",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fف.png?alt=media`]:
    "ف",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fق.png?alt=media`]:
    "ق",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fک.png?alt=media`]:
    "ک",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fگ.png?alt=media`]:
    "گ",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fل.png?alt=media`]:
    "ل",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fم.png?alt=media`]:
    "م",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fن.png?alt=media`]:
    "ن",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fو.png?alt=media`]:
    "و",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fہ.png?alt=media`]:
    "ہ",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fھ.png?alt=media`]:
    "ھ",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fی.png?alt=media`]:
    "ی",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fے.png?alt=media`]:
    "ے",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fء.png?alt=media`]:
    "ء",
  [`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/PSL%2Fں.png?alt=media`]:
    "ں",
};

module.exports = inversePslMapping;
